### ISSUE TITLE
Performance compared to ARKit

### ISSUE THREAD

**Issue by ghoshanjega** [HippoAR/react-native-arkit#96] opened 2017-10-23 20:51 UTC
I don't have any experience directly working on Swift so my go to fro everything is react native. Anyways after creating the sample stuff, it doesn't look that great compared to what I've seen in demos from Apple. Is this library directly working with native ARKit or does it have some sort of bridge that is hindering performance.

I would like to produce a production ready AR app, but react-native-arkit doesn't feel like the correct way to achieve it. Any thoughts guys? Any improvements coming up in the pipeline?

**Comment by macrozone** [comment] 2017-10-23 21:02
It uses ARKit directly, so the performance should be equal. The only performance problem could arise, when you use animated stuff by updating _some_ properties of 3d objects in a requestAnimation-frame loop (updating position or rotation should be fast, wheres updating shape is a bit slower, because it remounts the underlying SCNNode). The pure 3d render performance should be equal though, only updating properties is slower because of serialisation.

Do you do any special animation or things like dragging objects around? There are some tricks there

**Comment by ghoshanjega** [comment] 2017-10-23 22:55
Thanks for the response. The performance is better now after switching to release and code cleaning.

I do intend to use animations later on. Could you explain the initializing process. I see a white screen with "insufficient features"/ "None", etc. for quite some time and randomly the camera page loads. How does it actually initialize and how to get rid of the white screen?

**Comment by macrozone** [comment] 2017-10-24 08:32
@ghoshanjega which version do you use?

**Comment by ghoshanjega** [comment] 2017-10-24 16:40
0.3.0

**Comment by ghoshanjega** [comment] 2017-10-24 17:49
Just tried 0.4.0 the issue has been dealt with. And faster. Loading shapes and model is sometime not reliable.

Keep up the good work

**Comment by macrozone** [comment] 2017-11-05 22:32
@ghoshanjega thx! can i close that?

missing shapes should be fixed with 0.4.3 (just released). Otherwise a new issue with a reproduction would be awesome <3

**Closed by macrozone** 2017-11-05 22:32 UTC
