### ISSUE TITLE
How to use ARFaceTrackingConfiguration with react-native-arkit

### ISSUE THREAD

**Issue by DavidQL** [HippoAR/react-native-arkit#130] opened 2017-12-21 01:36 UTC
I need to use the [ARFaceTrackingConfiguration](https://developer.apple.com/documentation/arkit/arfacetrackingconfiguration) option for my ARkit project. Is there a way to specify that class as the scene's configuration?

**Comment by macrozone** [comment] 2017-12-21 10:54
@DavidQL not yet, but should be easy to add. Maybe you can try yourself and send a PR!

**Comment by macrozone** [comment] 2018-03-09 14:00
duplicate of https://github.com/HippoAR/react-native-arkit/issues/154

**Closed by macrozone** 2018-03-09 14:00 UTC

**Comment by emphaticaditya** [comment] 2022-08-29 20:45
any update on this?
